In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn import preprocessing

In [4]:
from sklearn.model_selection import train_test_split

In [23]:
from sklearn.naive_bayes import GaussianNB

In [24]:
from sklearn.metrics import accuracy_score

In [26]:
from sklearn.metrics import confusion_matrix

In [5]:
filepath = r"C:\Users\admin\Documents\LetsUpgrade\Notes\Day 24\train.csv"
train = pd.read_csv(filepath)

In [6]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [22]:
train.shape

(889, 12)

In [8]:
le = preprocessing.LabelEncoder()

In [13]:
le.fit(train['Sex'])

LabelEncoder()

In [14]:
le.classes_

array(['female', 'male'], dtype=object)

In [15]:
train['Sex'] = le.transform(train['Sex'])

In [16]:
le.fit(train['Embarked'])

LabelEncoder()

In [17]:
le.classes_

array(['C', 'Q', 'S'], dtype=object)

In [18]:
train['Embarked'] = le.transform(train['Embarked'])

In [19]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin  Embarked  
0         A/5 21171   7.2500   NaN         2  
1          PC 17599  71.2833   C85         0  
2  STON/O2. 3101282   7.9250   NaN         2  
3            113803  53.1000  C123         2  
4            373450   8.0500   NaN         2

In [32]:
y_list = ['Pclass','Sex','SibSp','Parch','Embarked']

In [38]:
from sklearn.naive_bayes import *

In [49]:
for i in y_list:
    y = train[i]
    X = train.drop([i,'PassengerId','Name','Ticket','Cabin'],axis = 1)
    X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state = 0)
    clf = BernoulliNB()
    y_pred = clf.fit(X_train,y_train).predict(X_test)
    print('Accuracy score of {dv} and remaining is:'.format(dv = i),accuracy_score(y_test,y_pred,normalize = True))
    print('Confusion matrix of {dv}:\n'.format(dv=i),confusion_matrix(y_test,y_pred))

    

Accuracy score of Pclass and remaining is: 0.5917602996254682
Confusion matrix of Pclass:
 [[ 30   8  32]
 [  9  10  30]
 [ 24   6 118]]
Accuracy score of Sex and remaining is: 0.7453183520599251
Confusion matrix of Sex:
 [[ 49  49]
 [ 19 150]]
Accuracy score of SibSp and remaining is: 0.6891385767790262
Confusion matrix of SibSp:
 [[162  20   0   0   0   0   0]
 [ 43  22   0   0   0   0   0]
 [  6   2   0   0   0   0   0]
 [  5   2   0   0   0   0   0]
 [  2   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0]
 [  2   0   0   0   0   0   0]]
Accuracy score of Parch and remaining is: 0.7153558052434457
Confusion matrix of Parch:
 [[182  16   0   0   0]
 [ 31   9   0   0   0]
 [ 24   3   0   0   0]
 [  1   0   0   0   0]
 [  1   0   0   0   0]]
Accuracy score of Embarked and remaining is: 0.7340823970037453
Confusion matrix of Embarked:
 [[  0   0  49]
 [  0   0  22]
 [  0   0 196]]
