# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
a = np.random.random((3,3,3))
print(a.shape)

(3, 3, 3)


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
b = np.array([[1,2,3,5,4],[6,4,8,9,6],[12,45,67,89,3],[5,4,2,67,88],[9,18,21,45,668]])
m = b.shape[0]
n = b.shape[1]
k=1
for i in range(0,m-1):
    for j in range(0,n):
        if(i==j):
            b[i+1][j] = k
            k+=1
b

array([[  1,   2,   3,   5,   4],
       [  1,   4,   8,   9,   6],
       [ 12,   2,  67,  89,   3],
       [  5,   4,   3,  67,  88],
       [  9,  18,  21,   4, 668]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
c= np.zeros((8,8))
m = c.shape[0]
n = c.shape[1]
for i in range(m):
    for j in range(n):
        if(i%2 == 0 and j%2!=0):
            c[i][j] = 1
        if(i%2!=0 and j%2 == 0):
            c[i][j] = 1
            
c


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

# 4. Normalize a 5x5 random matrix

In [4]:
d = np.random.random((5,5))
print(d)
dmax,dmin = d.max(),d.min()
d = (d-dmin)/(dmax-dmin)
print("After normalization:")
print(d)

[[0.43730847 0.96631448 0.18751785 0.69617992 0.67753203]
 [0.97417403 0.66943681 0.8771026  0.68480454 0.22720777]
 [0.86358878 0.33976263 0.63696392 0.64474542 0.92909089]
 [0.92396281 0.18941625 0.33746327 0.17525302 0.9051403 ]
 [0.14670301 0.04240081 0.76883738 0.30742585 0.19955685]]
After normalization:
[[0.42382379 0.99156496 0.15574288 0.70165047 0.68163713]
 [1.         0.67294915 0.89582075 0.68944214 0.19833899]
 [0.88131742 0.3191354  0.63809852 0.6464498  0.95161576]
 [0.94611219 0.15778028 0.31666767 0.14257998 0.92591144]
 [0.11193946 0.         0.77962808 0.28443084 0.1686634 ]]


# 5.  How to find common values between two arrays?

In [5]:
a = np.array([1,2,5,73,21])
b = np.array([3,1,4,6,73])
for i in a:
    if i in b:
        print(i)


1
73


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
print("Yesterday:",yesterday)
today = np.datetime64('today','D')
print("Today: ",today)
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
print("Tomorrow:",tomorrow)

Yesterday: 2020-07-27
Today:  2020-07-28
Tomorrow: 2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [7]:
a = np.random.random(4)
b = np.random.random(4)
equal = np.array_equal(a,b)
print(equal)

False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [8]:
a = np.random.random(10)
print(a)
b = a.argmax()
a[b] = 0.0
print(a)

[0.12338753 0.85929532 0.85260778 0.93226253 0.3909321  0.93291182
 0.28717885 0.82609454 0.93806508 0.89795818]
[0.12338753 0.85929532 0.85260778 0.93226253 0.3909321  0.93291182
 0.28717885 0.82609454 0.         0.89795818]


# 9. How to print all the values of an array?

In [9]:
a = np.arange(5)
for i in a:
    print(i)

0
1
2
3
4


# 10.Subtract the mean of each row of a matrix

In [10]:
x = np.array([[2,4,5,78,23],[1,5,3,1,2]],dtype = np.float64)
x_bar = x.mean(axis=1)
m = x.shape[0]
n = x.shape[1]
for i in range(m):
    for j in range(n):
        x[i][j] -= x_bar[i]
print(x_bar)
x

[22.4  2.4]


array([[-20.4, -18.4, -17.4,  55.6,   0.6],
       [ -1.4,   2.6,   0.6,  -1.4,  -0.4]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [11]:
z = np.ones(10)
i = np.random.randint(0,len(z),20)

In [12]:
np.add.at(z,i,1)
print(z)

[3. 6. 3. 2. 4. 2. 1. 5. 3. 1.]


# 12.How to get the diagonal of a dot product?

In [13]:
a = np.array([[2,4],[3,5]])
b = np.array([[3,5],[8,9]])
c = a@b
print(c)
np.diag(c)

[[38 46]
 [49 60]]


array([38, 60])

# 13.How to find the most frequent value in an array?

In [14]:
e = np.array([5,5,5,1,2,3,5,2,3,5])
print(e)
print("Most frequent value in the above array:")
print(np.bincount(e).argmax())

[5 5 5 1 2 3 5 2 3 5]
Most frequent value in the above array:
5


# 14.How to get the n largest values of an array

In [15]:
n = int(input("Enter n value:"))
f = np.array([2,3,4,6,88,33,2])
f = sorted(f)
print(f[:-(n+1):-1])


Enter n value:3
[88, 33, 6]


# 15.How to create a record array from a regular array?

In [16]:
x = np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [17]:
x = x.view(np.recarray)
x

rec.array([1, 2, 3, 4],
          dtype=int32)